services:
  - type: static
    name: frontend
    runtime: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    rewrites:
      - source: /*
        destination: /index.html